# Generated by Django 5.2.15 on 2026-06-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('focus-areas', 'Focus Areas'), ('conditions', 'Conditions We Treat'), ('treatments', 'Our Treatments')], db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short summary for hub listing cards.')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description for search engines.')),
                ('description', models.TextField(blank=True, help_text='Main page introduction and rich content shown at the top of the detail page.')),
                ('benefits_heading', models.CharField(blank=True, default='Why choose our Calgary clinic', max_length=200)),
                ('faq_intro', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Highlight on homepage and treatment hub (treatments only).')),
                ('menu_column', models.PositiveSmallIntegerField(default=1, help_text='Mega menu column: 1 = left, 2 = right.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
                'ordering': ['section', 'sort_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('section', 'slug'), name='unique_content_page_slug')],
            },
        ),
        migrations.CreateModel(
            name='PageContentBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_items', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageContentFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Content section',
                'verbose_name_plural': 'Content sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
