# Generated by Django 5.2.15 on 2026-06-18 23:31

from django.db import migrations, models


def assign_default_images(apps, schema_editor):
    # Use the historical model (apps.get_model) instead of the live model so
    # this migration only touches columns that exist at this point in history.
    # The live ContentPage gains fields like ``typical_sessions`` in later
    # migrations, and importing the live helper here would try to select them
    # on a fresh database before those columns exist.
    from django.core.files import File

    from website.page_images import (
        ASSETS_DIR,
        FALLBACK_IMAGE,
        resolve_image_filename,
    )

    ContentPage = apps.get_model('website', 'ContentPage')
    pages = ContentPage.objects.order_by('section', 'sort_order', 'id')
    if not pages.exists():
        return

    for page in pages:
        filename = resolve_image_filename(page.slug, page.section, page.title)
        source_path = ASSETS_DIR / filename
        if not source_path.exists():
            source_path = ASSETS_DIR / FALLBACK_IMAGE
        if not source_path.exists():
            continue

        with source_path.open('rb') as image_file:
            page.image.save(f'{page.slug}.jpg', File(image_file), save=False)
        page.image_alt = f'{page.title} at Medpro Physio Calgary'
        page.save(update_fields=['image', 'image_alt'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_content_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero image for the detail page and hub listing card.', upload_to='content_pages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the page image. Leave blank to use the page title.', max_length=200),
        ),
        migrations.RunPython(assign_default_images, migrations.RunPython.noop),
    ]
