# Generated by Django 5.2.15 on 2026-06-19 08:13

import django.db.models.deletion
from django.db import migrations, models


def seed_treatment_structured_content(apps, schema_editor):
    ContentPage = apps.get_model('website', 'ContentPage')
    PageAssessmentStep = apps.get_model('website', 'PageAssessmentStep')
    PageTreatmentMethod = apps.get_model('website', 'PageTreatmentMethod')
    PageRecoveryPhase = apps.get_model('website', 'PageRecoveryPhase')
    PageCaseStudy = apps.get_model('website', 'PageCaseStudy')
    PageContentBenefit = apps.get_model('website', 'PageContentBenefit')
    PageContentFAQ = apps.get_model('website', 'PageContentFAQ')
    PageContentSection = apps.get_model('website', 'PageContentSection')

    from website.treatment_content import all_treatment_content

    for slug, data in all_treatment_content().items():
        try:
            page = ContentPage.objects.get(section='treatments', slug=slug)
        except ContentPage.DoesNotExist:
            continue

        page.summary = data.get('summary', page.summary)
        page.meta_description = data.get('meta_description', '')
        page.description = data.get('description', '')
        page.typical_sessions = data.get('typical_sessions', '')
        page.first_improvement = data.get('first_improvement', '')
        page.recovery_timeline = data.get('recovery_timeline', '')
        page.benefits_heading = data.get('benefits_heading', 'What this treatment helps with')
        page.faq_intro = data.get('faq_intro', '')
        page.save()

        PageContentSection.objects.filter(page=page).delete()
        PageContentBenefit.objects.filter(page=page).delete()
        PageContentFAQ.objects.filter(page=page).delete()
        PageAssessmentStep.objects.filter(page=page).delete()
        PageTreatmentMethod.objects.filter(page=page).delete()
        PageRecoveryPhase.objects.filter(page=page).delete()
        PageCaseStudy.objects.filter(page=page).delete()

        for index, (title, body) in enumerate(data.get('assessment_steps', [])):
            PageAssessmentStep.objects.create(
                page=page, title=title, body=body, sort_order=index,
            )
        for index, (title, body) in enumerate(data.get('treatment_methods', [])):
            PageTreatmentMethod.objects.create(
                page=page, title=title, body=body, sort_order=index,
            )
        for index, (phase, timeframe, body) in enumerate(data.get('recovery_phases', [])):
            PageRecoveryPhase.objects.create(
                page=page, phase=phase, timeframe=timeframe, body=body, sort_order=index,
            )
        for index, case in enumerate(data.get('case_studies', [])):
            PageCaseStudy.objects.create(
                page=page,
                patient_label=case['patient_label'],
                issue=case['issue'],
                approach=case['approach'],
                outcome=case['outcome'],
                timeline=case['timeline'],
                sort_order=index,
            )
        for index, benefit in enumerate(data.get('benefits', [])):
            PageContentBenefit.objects.create(page=page, text=benefit, sort_order=index)
        for index, (question, answer) in enumerate(data.get('faqs', [])):
            PageContentFAQ.objects.create(
                page=page, question=question, answer=answer, sort_order=index,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_tmj_jaw_care_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='first_improvement',
            field=models.CharField(blank=True, help_text='When patients often notice improvement (treatments only).', max_length=80),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='recovery_timeline',
            field=models.CharField(blank=True, help_text='Typical full recovery timeframe (treatments only).', max_length=80),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='typical_sessions',
            field=models.CharField(blank=True, help_text='Typical number of sessions (treatments only).', max_length=80),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a hero image file for the detail page and hub card. JPG or PNG recommended.', upload_to='content_pages/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PageAssessmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_steps', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Assessment step',
                'verbose_name_plural': 'Assessment steps',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_label', models.CharField(max_length=120)),
                ('issue', models.CharField(max_length=200)),
                ('approach', models.TextField()),
                ('outcome', models.TextField()),
                ('timeline', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageRecoveryPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=120)),
                ('timeframe', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_phases', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Recovery phase',
                'verbose_name_plural': 'Recovery phases',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageTreatmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_methods', to='website.contentpage')),
            ],
            options={
                'verbose_name': 'Treatment method',
                'verbose_name_plural': 'Treatment methods',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_treatment_structured_content, migrations.RunPython.noop),
    ]
