# Generated by Django 5.2.15 on 2026-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_add_mva_focus_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, help_text='Static image path, e.g. images/blog-wcb-workplace-injury.jpg', max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField()),
                ('author', models.CharField(default='Medpro Physiotherapy Team', max_length=100)),
                ('reading_time', models.CharField(blank=True, default='5 min read', max_length=30)),
                ('content', models.TextField(blank=True, help_text='Main article body (HTML). Used when sections JSON is empty.')),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('related_services', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
