"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    """Load KEY=VALUE pairs from a .env file into os.environ (no dependency).

    Existing environment variables always take precedence, so values exported
    in the shell override the file.
    """
    if not path.exists():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / '.env')


def _env_flag(name: str, default: str = 'false') -> bool:
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-only-change-me-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Local .env should set DEBUG=true. Production defaults to false so unknown
# URLs show the branded 404 instead of Django's debug error page.
DEBUG = _env_flag('DEBUG', 'false')

_allowed_hosts = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').strip()
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',') if host.strip()]

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in _csrf_origins.split(',') if origin.strip()
]

# DigitalOcean App Platform injects the app's public hostname/URL automatically.
# Trust it (plus the shared *.ondigitalocean.app domain) so the site works even
# before a custom ALLOWED_HOSTS value is configured.
_do_domain = os.environ.get('APP_DOMAIN', '').strip()
_do_url = os.environ.get('APP_URL', '').strip()
if _do_domain and _do_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_do_domain)
if '.ondigitalocean.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.ondigitalocean.app')
for _origin in (_do_url, f'https://{_do_domain}' if _do_domain else ''):
    _origin = _origin.strip()
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)
if 'https://*.ondigitalocean.app' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://*.ondigitalocean.app')

# App Platform injects APP_DOMAIN / APP_URL. Never serve debug 404/500 pages
# on the live clinic site, even if DEBUG=true was left in the dashboard.
if (_do_domain or _do_url) and not _env_flag('ALLOW_DEBUG'):
    DEBUG = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_summernote',
    'bookings',
    'website',
    'panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.site',
                'panel.context_processors.panel_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# PostgreSQL is required for development and production.
# Priority: DATABASE_URL (DigitalOcean) > POSTGRES_* / DB_* env vars.
# Set USE_SQLITE=true only as an emergency local override.

def _postgres_config_from_env():
    db_name = (
        os.environ.get('POSTGRES_DB')
        or os.environ.get('DB_NAME')
        or ''
    ).strip()
    db_user = (
        os.environ.get('POSTGRES_USER')
        or os.environ.get('DB_USER')
        or ''
    ).strip()
    if not (db_name and db_user):
        return None

    raw_port = (
        os.environ.get('POSTGRES_PORT')
        or os.environ.get('DB_PORT')
        or '5432'
    ).strip()
    try:
        port = int(raw_port)
    except ValueError:
        port = 0
    if port < 1 or port > 65535:
        raise ImproperlyConfigured(
            f'PostgreSQL port must be between 1 and 65535 (got {raw_port!r}).'
        )

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': (
            os.environ.get('POSTGRES_PASSWORD')
            or os.environ.get('DB_PASSWORD')
            or ''
        ),
        'HOST': (
            os.environ.get('POSTGRES_HOST')
            or os.environ.get('DB_HOST')
            or 'localhost'
        ),
        'PORT': str(port),
        'CONN_MAX_AGE': 600,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }


_db_url = os.environ.get('DATABASE_URL', '').strip()
_force_sqlite = _env_flag('USE_SQLITE')

if _force_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif _db_url:
    DATABASES = {
        'default': dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    _postgres = _postgres_config_from_env()
    if not _postgres:
        raise ImproperlyConfigured(
            'PostgreSQL is required. Set DATABASE_URL or POSTGRES_DB / POSTGRES_USER '
            '(and host, port, password) in the environment.'
        )
    DATABASES = {'default': _postgres}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'medpro-cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Calgary, Alberta uses America/Edmonton (Mountain Time, MST/MDT).

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en-ca')

TIME_ZONE = os.environ.get('TIME_ZONE', 'America/Edmonton')

USE_I18N = True

USE_TZ = True


# Static & media — local filesystem by default; Cloudflare R2 when USE_R2=True.

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

USE_R2 = _env_flag('USE_R2', 'false')
USE_R2_MEDIA = _env_flag('USE_R2_MEDIA', 'false')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if USE_R2:
    _r2_required = (
        'R2_ACCESS_KEY',
        'R2_SECRET_KEY',
        'R2_BUCKET_NAME',
        'R2_ENDPOINT_URL',
        'R2_PUBLIC_URL',
    )
    if any(not os.environ.get(key, '').strip() for key in _r2_required):
        raise ImproperlyConfigured('USE_R2=True requires R2_* variables in .env')

    AWS_ACCESS_KEY_ID = os.environ['R2_ACCESS_KEY']
    AWS_SECRET_ACCESS_KEY = os.environ['R2_SECRET_KEY']
    AWS_STORAGE_BUCKET_NAME = os.environ['R2_BUCKET_NAME']
    AWS_S3_ENDPOINT_URL = os.environ['R2_ENDPOINT_URL'].rstrip('/')
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False

    _public_base = os.environ['R2_PUBLIC_URL'].rstrip('/')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get(
        'R2_CUSTOM_DOMAIN',
        _public_base.replace('https://', '').replace('http://', ''),
    )

    # Keep local FileSystemStorage in DEBUG so {% static %} resolves to
    # /static/... and new files work without an R2 upload. Production still
    # serves from R2 after collectstatic/deploy.
    if not DEBUG:
        STORAGES['staticfiles'] = {'BACKEND': 'config.storages.StaticStorage'}
        STATIC_URL = f'{_public_base}/static/'

    if USE_R2_MEDIA:
        STORAGES['default'] = {'BACKEND': 'config.storages.MediaStorage'}
        MEDIA_URL = f'{_public_base}/media/'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_flag('SECURE_SSL_REDIRECT', 'true')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

LOGIN_URL = '/panel/login/'
LOGIN_REDIRECT_URL = '/panel/'
LOGOUT_REDIRECT_URL = '/panel/login/'

SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '320',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['insert', ['link']],
            ['view', ['fullscreen', 'codeview']],
        ],
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Booking configuration
# Concurrent bookings allowed for physiotherapy. Other services use Service.slot_capacity (usually 1).
BOOKING_SLOT_CAPACITY = int(os.environ.get('BOOKING_SLOT_CAPACITY', '5'))

# Public form spam protection (contact + online booking).
SPAM_MIN_FORM_SECONDS = int(os.environ.get('SPAM_MIN_FORM_SECONDS', '2'))
SPAM_MAX_FORM_SECONDS = int(os.environ.get('SPAM_MAX_FORM_SECONDS', '7200'))
SPAM_CONTACT_LIMIT = int(os.environ.get('SPAM_CONTACT_LIMIT', '3'))
SPAM_CONTACT_WINDOW = int(os.environ.get('SPAM_CONTACT_WINDOW', '3600'))
SPAM_BOOKING_LIMIT = int(os.environ.get('SPAM_BOOKING_LIMIT', '5'))
SPAM_BOOKING_WINDOW = int(os.environ.get('SPAM_BOOKING_WINDOW', '3600'))
TURNSTILE_SITE_KEY = os.environ.get('TURNSTILE_SITE_KEY', '').strip()
TURNSTILE_SECRET = (
    os.environ.get('TURNSTILE_SECRET', '').strip()
    or os.environ.get('TURNSTILE_SECRET_KEY', '').strip()
)
TURNSTILE_SECRET_KEY = TURNSTILE_SECRET
TURNSTILE_HOSTNAMES = os.environ.get('TURNSTILE_HOSTNAMES', '').strip()

# Absolute base URL used when building links inside notification emails.
# Must be a single origin (not a comma-separated list).
_site_base = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000').strip()
SITE_BASE_URL = _site_base.split(',')[0].strip().rstrip('/')


# Email
# Defaults to the console backend so bookings work in development without SMTP.
# For production set EMAIL_BACKEND to the SMTP backend and provide credentials.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_flag('EMAIL_USE_TLS', 'true')
EMAIL_USE_SSL = _env_flag('EMAIL_USE_SSL', 'false')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Medpro Physiotherapy <no-reply@medprophysiotherapy.ca>',
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

def _email_list(raw: str) -> list[str]:
    emails = []
    seen = set()
    for part in (raw or '').replace(';', ',').split(','):
        email = part.strip()
        if not email:
            continue
        key = email.lower()
        if key in seen:
            continue
        seen.add(key)
        emails.append(email)
    return emails


# Comma-separated clinic inboxes for booking and contact alerts.
CLINIC_NOTIFICATION_EMAILS = _email_list(
    os.environ.get('CLINIC_NOTIFICATION_EMAIL', 'Umair94m@gmail.com')
)
CLINIC_NOTIFICATION_EMAIL = ','.join(CLINIC_NOTIFICATION_EMAILS)


# Google Calendar integration
# A calendar invite (.ics) is always attached to booking emails, so Gmail and
# Google Calendar can add the appointment automatically. Optionally, enable the
# Google Calendar API to create the event directly on a shared clinic calendar.
GOOGLE_CALENDAR_ENABLED = _env_flag('GOOGLE_CALENDAR_ENABLED', 'false')
GOOGLE_CALENDAR_ID = os.environ.get('GOOGLE_CALENDAR_ID', 'primary').strip()
GOOGLE_CALENDAR_CREDENTIALS_FILE = os.environ.get(
    'GOOGLE_CALENDAR_CREDENTIALS_FILE',
    '',
).strip()
