# Generated by Django 5.2.15 on 2026-06-18 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='practitioners/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('buffer_minutes', models.PositiveIntegerField(default=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='bookings_cu_email_bec9bd_idx'), models.Index(fields=['phone'], name='bookings_cu_phone_a48e0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PractitionerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_services', to='bookings.practitioner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_services', to='bookings.service')),
            ],
            options={
                'unique_together': {('practitioner', 'service')},
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='services',
            field=models.ManyToManyField(related_name='practitioners', through='bookings.PractitionerService', to='bookings.service'),
        ),
        migrations.CreateModel(
            name='PractitionerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bookings.practitioner')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['practitioner', 'day_of_week'], name='bookings_pr_practit_32bb9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('practitioner', models.ForeignKey(blank=True, help_text='Leave blank for clinic-wide closures.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='bookings.practitioner')),
            ],
            options={
                'ordering': ['exception_date'],
                'indexes': [models.Index(fields=['exception_date'], name='bookings_sc_excepti_af549f_idx'), models.Index(fields=['practitioner', 'exception_date'], name='bookings_sc_practit_29a3e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], default='confirmed', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('online', 'Online'), ('phone', 'Phone'), ('walk_in', 'Walk-in')], default='online', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bookings.customer')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='bookings.practitioner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bookings.service')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'status'], name='bookings_ap_start_d_e8f542_idx'), models.Index(fields=['confirmation_token'], name='bookings_ap_confirm_4f87da_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('practitioner', 'start_datetime'), name='unique_active_practitioner_slot')],
            },
        ),
    ]
