# Generated by Django 5.2.15 on 2026-06-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='practice_perfect_appointment_id',
            field=models.CharField(blank=True, help_text='Appointment ID returned by Practice Perfect or integration middleware.', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practice_perfect_last_sync_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practice_perfect_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practice_perfect_sync_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending sync'), ('synced', 'Synced'), ('failed', 'Sync failed')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practice_perfect_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='practice_perfect_id',
            field=models.CharField(blank=True, help_text='Practice Perfect provider ID for calendar sync.', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='practice_perfect_id',
            field=models.CharField(blank=True, help_text='Practice Perfect service or fee code ID for calendar sync.', max_length=100),
        ),
    ]
