# Generated by Django 5.2.15 on 2026-07-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_appointment_practice_perfect_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='practice_perfect_appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='practice_perfect_last_sync_attempt_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='practice_perfect_sync_error',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='practice_perfect_sync_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='practice_perfect_synced_at',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='practice_perfect_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='practice_perfect_id',
        ),
    ]
