# Generated by Django 5.2.15 on 2026-08-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_appointment_practice_perfect_appointment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_unavailable', models.BooleanField(default=False, help_text='When checked, this service cannot be booked on this weekday.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bookings.service')),
            ],
            options={
                'ordering': ['service', 'day_of_week'],
                'indexes': [models.Index(fields=['service', 'day_of_week'], name='bookings_se_service_4bb4f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('service', 'day_of_week'), name='unique_service_day_schedule')],
            },
        ),
    ]
